# Generated by Django 5.0.7 on 2024-08-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CallType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='DistributionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FundStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeNumber',
            fields=[
                ('number', models.SmallIntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('objective', models.TextField(blank=True, max_length=300)),
                ('investment_period', models.IntegerField(default=0)),
                ('divestment_period', models.IntegerField(default=0)),
                ('life', models.IntegerField(default=0)),
                ('target_commitment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('man_fee', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.currency')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.fundstructure')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=400, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.country')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.industry')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invested_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('realised_proceeds', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valuation', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('IRR', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('MOIC', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.company')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investment')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('logo', models.ImageField(default='no_picture.png', null=True, upload_to='investors')),
                ('reg_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.country')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.investortype')),
            ],
        ),
        migrations.CreateModel(
            name='FundClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number', models.SmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('prudencial_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('committment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fund_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=100)),
                ('main_contact', models.BooleanField(default=False)),
                ('adv_board_rep', models.BooleanField(default=False)),
                ('invest_comm_rep', models.BooleanField(default=False)),
                ('reports', models.BooleanField(default=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='CommittedCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund_interest', models.DecimalField(decimal_places=3, max_digits=4)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('document', models.FileField(null=True, upload_to='investors')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('distribution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.distributiontype')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.noticenumber')),
            ],
        ),
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('call_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.calltype')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.noticenumber')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.expensetype')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.incometype')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='UnrealisedGains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='UnrealisedLosses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
    ]
