# Generated by Django 5.0.7 on 2024-07-17 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allocation_rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='call_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length='30')),
                ('code', models.TextField(max_length='4')),
            ],
        ),
        migrations.CreateModel(
            name='distribution_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fund_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='investor_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='notice_number',
            fields=[
                ('number', models.SmallIntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('objective', models.TextField(blank=True, max_length=300)),
                ('investment_period', models.IntegerField(default=0)),
                ('divestment_period', models.IntegerField(default=0)),
                ('life', models.IntegerField(default=0, null=True)),
                ('target_commitment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commitment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('drawn_capital', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('undrawn_capital', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('distributions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('portfolio_count', models.IntegerField(default=0)),
                ('man_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.currency')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.fund_structure')),
            ],
        ),
        migrations.CreateModel(
            name='investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('logo', models.ImageField(default='no_picture.png', null=True, upload_to='investors')),
                ('reg_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('key_contact', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(default='', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.country')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.investor_type')),
            ],
        ),
        migrations.CreateModel(
            name='fund_close',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number', models.SmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fund_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=100)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='investor_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('document', models.FileField(null=True, upload_to='investors')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.distribution_type')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.notice_number')),
            ],
        ),
        migrations.CreateModel(
            name='capital_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.call_type')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.investor')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.notice_number')),
            ],
        ),
    ]
