# Generated by Django 5.1.5 on 2025-01-31 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committedcapital',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committedcapital',
            name='final_close',
            field=models.BooleanField(default=False),
        ),
    ]
