# Generated by Django 5.0.7 on 2024-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
