# Generated by Django 5.1.6 on 2025-08-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcall',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
