# Generated by Django 5.1.6 on 2025-03-23 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_end', models.DateField(null=True)),
                ('fee_frequency', models.CharField(blank=True, choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-Annually'), ('A', 'Annually')], max_length=1, null=True)),
                ('investment_period_fee_basis', models.CharField(blank=True, choices=[('C', 'Committed-Capital'), ('I', 'Invested-Capital'), ('A', 'Net-Asset-Value')], max_length=1, null=True)),
                ('divest_period_fee_basis', models.CharField(blank=True, choices=[('C', 'Committed-Capital'), ('I', 'Invested-Capital'), ('A', 'Net-Asset-Value')], max_length=1, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('update_flag', models.BooleanField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
            ],
        ),
    ]
