# Generated by Django 5.1.6 on 2025-08-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capitalcall',
            old_name='notice',
            new_name='notice_number',
        ),
    ]
