# Generated by Django 5.1.6 on 2025-08-26 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_capitalcall_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitalcall',
            options={'ordering': ['-date', 'investor__name']},
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='allocation_rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.allocationrule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
