# Generated by Django 5.1.6 on 2025-08-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_notice_capitalcall_notice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticenumber',
            name='notice_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
