# Generated by Django 5.0.7 on 2024-07-17 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_currency_code_alter_currency_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=400, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.country')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.industry')),
            ],
        ),
        migrations.CreateModel(
            name='investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('invested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.company')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.instrument')),
            ],
        ),
    ]
