# Generated by Django 5.1.5 on 2025-01-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_committedcapital_date_committedcapital_final_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committedcapital',
            name='series_number',
        ),
    ]
