# Generated by Django 5.0.7 on 2024-08-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_committedcapital_fund_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calltype',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='capitalcall',
            old_name='notice',
            new_name='notice_number',
        ),
        migrations.RenameField(
            model_name='distributiontype',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='committedcapital',
            name='fund_interest',
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
