# Generated by Django 5.1.6 on 2025-08-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_noticenumber_notice_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
