# Generated by Django 5.0.7 on 2024-07-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_industry_instrument_company_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investment')),
            ],
        ),
    ]
