# Generated by Django 5.0.7 on 2024-07-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_disbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_close',
            name='committment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fund_close',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fund_close',
            name='prudencial_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
