# Generated by Django 5.1.6 on 2025-08-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='number',
            field=models.SmallIntegerField(null=True),
        ),
    ]
