# Generated by Django 5.0.7 on 2024-07-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_fund_close_committment_fund_close_limit_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'industries'},
        ),
    ]
