# Generated by Django 5.1.6 on 2025-08-29 22:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_frequency_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
        migrations.RenameField(
            model_name='managementfees',
            old_name='period_end',
            new_name='period_end_date',
        ),
        migrations.RenameField(
            model_name='managementfees',
            old_name='period_start',
            new_name='period_start_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='IRR',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='MOIC',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='invested_amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='realised_proceeds',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='valuation',
        ),
        migrations.RemoveField(
            model_name='managementfees',
            name='update_flag',
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='fee_year_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='investment_period_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='managementfees',
            name='applicable_fee_rate',
            field=models.DecimalField(decimal_places=5, default=0.02, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementfees',
            name='basis_type',
            field=models.CharField(choices=[('C', 'Committed-Capital'), ('I', 'Invested-Capital'), ('A', 'Net-Asset-Value')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementfees',
            name='calculated_basis',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementfees',
            name='calculation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementfees',
            name='capital_call',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_fee_schedule', to='manager.capitalcall'),
        ),
        migrations.AddField(
            model_name='managementfees',
            name='gross_fee_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementfees',
            name='investor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.investor'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='managementfees',
            constraint=models.UniqueConstraint(fields=('fund', 'period_start_date', 'period_end_date'), name='unique_fee_period'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='manager.investment'),
        ),
        migrations.AlterUniqueTogether(
            name='valuation',
            unique_together={('investment', 'valuation_date')},
        ),
    ]
