# Generated by Django 5.1.6 on 2025-08-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_valuation_delete_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementfees',
            name='applicable_fee_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
