# Generated by Django 5.0.7 on 2024-07-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_currency_options_alter_fund_man_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='adv_board_rep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='invest_comm_rep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='main_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='IRR',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='investment',
            name='MOIC',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='investment',
            name='realised_proceeds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investment',
            name='valuation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investment',
            name='committed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investment',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
