# Generated by Django 5.1.6 on 2025-08-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_managementfees_applicable_fee_rate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='committedcapital',
            constraint=models.CheckConstraint(condition=models.Q(('fund__isnull', True), _negated=True), name='fund_required'),
        ),
    ]
