# Generated by Django 5.0.7 on 2024-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_contact_adv_board_rep_contact_invest_comm_rep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='life',
            field=models.IntegerField(default=0),
        ),
    ]
