# Generated by Django 5.1.6 on 2025-08-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_committedcapital_fund_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementfees',
            name='investor',
        ),
    ]
