# Generated by Django 5.1.6 on 2025-08-30 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_managementfees_investor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundparameter',
            options={'verbose_name': 'Fund Parameter', 'verbose_name_plural': 'Fund Parameters'},
        ),
        migrations.RenameField(
            model_name='fundparameter',
            old_name='fee_year_end_month',
            new_name='period9_end_month',
        ),
        migrations.RemoveField(
            model_name='fundparameter',
            name='year_end',
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='fiscal_year_end_month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Dec', max_length=3),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period10_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period11_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period12_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period1_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period2_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period3_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period4_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period5_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period6_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period7_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='period8_end_month',
            field=models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fundparameter',
            name='divest_period_fee_basis',
            field=models.CharField(choices=[('C', 'Committed-Capital'), ('I', 'Invested-Capital'), ('A', 'Net-Asset-Value')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='fundparameter',
            name='fee_frequency',
            field=models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-Annually'), ('A', 'Annually')], default='Q', max_length=1),
        ),
        migrations.AlterField(
            model_name='fundparameter',
            name='fund',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='manager.fund'),
        ),
        migrations.AlterField(
            model_name='fundparameter',
            name='investment_period_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fundparameter',
            name='investment_period_fee_basis',
            field=models.CharField(choices=[('C', 'Committed-Capital'), ('I', 'Invested-Capital'), ('A', 'Net-Asset-Value')], default='C', max_length=1),
        ),
    ]
