# Generated by Django 5.0.7 on 2024-08-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_expensetype_incometype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingexpense',
            old_name='income_type',
            new_name='expense_type',
        ),
    ]
