# Generated by Django 5.1.6 on 2025-08-30 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_fundparameter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementfees',
            options={'ordering': ['-period_end_date', 'fund'], 'verbose_name_plural': 'Management fees'},
        ),
        migrations.RemoveConstraint(
            model_name='managementfees',
            name='unique_fee_period',
        ),
        migrations.AlterUniqueTogether(
            name='managementfees',
            unique_together={('fund', 'period_start_date', 'period_end_date')},
        ),
        migrations.AddField(
            model_name='managementfees',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementfees',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementfees',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementfees',
            name='prorated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementfees',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='managementfees',
            name='applicable_fee_rate',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='managementfees',
            name='basis_type',
            field=models.CharField(choices=[('C', 'Committed-Capital'), ('I', 'Invested-Capital'), ('A', 'Net-Asset-Value')], max_length=2),
        ),
        migrations.AlterField(
            model_name='managementfees',
            name='calculated_basis',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='managementfees',
            name='capital_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_fees', to='manager.capitalcall'),
        ),
        migrations.AlterField(
            model_name='managementfees',
            name='gross_fee_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.RemoveField(
            model_name='managementfees',
            name='calculation_date',
        ),
    ]
