# Generated by Django 5.1.6 on 2025-08-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_managementfees_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='IRR',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='investment',
            name='MOIC',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='investment',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investment',
            name='realised_proceeds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investment',
            name='valuation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
