# Generated by Django 5.0.7 on 2024-08-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_rename_income_type_operatingexpense_expense_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capitalcall',
            old_name='type',
            new_name='call_type',
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='type',
            new_name='distribution_type',
        ),
    ]
