# Generated by Django 5.1.6 on 2025-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_investment_irr_investment_moic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcall',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
