# Generated by Django 5.1.6 on 2025-09-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_capitalcall_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
