# Generated by Django 5.0.7 on 2024-08-04 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_unrealisedtypes_unrealisedgainsorlosses'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnrealisedGains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.CreateModel(
            name='UnrealisedLosses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
        ),
        migrations.DeleteModel(
            name='UnrealisedGainsOrLosses',
        ),
        migrations.DeleteModel(
            name='UnrealisedTypes',
        ),
    ]
