# Generated by Django 5.1.6 on 2025-09-08 15:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundparameter',
            name='vat_on_fees',
            field=models.BooleanField(default=False, help_text='Whether the fund manager is VAT registered'),
        ),
        migrations.AddField(
            model_name='fundparameter',
            name='vat_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.15'), help_text='VAT rate to apply (e.g., 0.15 for 15%)', max_digits=5),
        ),
    ]
