# Generated by Django 5.1.6 on 2025-09-08 15:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_fundparameter_vat_on_fees_fundparameter_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementfees',
            name='total_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='managementfees',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='managementfees',
            name='vat_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementfees',
            name='vat_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=5),
        ),
    ]
