# Generated by Django 5.1.6 on 2025-09-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_managementfees_total_fee_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundparameter',
            old_name='vat_on_fees',
            new_name='vat_registered',
        ),
    ]
