# Generated by Django 5.1.6 on 2025-09-08 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_rename_vat_on_fees_fundparameter_vat_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='calltype',
            name='category',
            field=models.CharField(choices=[('INVESTMENT', 'Investment'), ('EXPENSE', 'Expense'), ('FEE', 'Fee')], default='EXPENSE', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocation_percentage', models.DecimalField(decimal_places=4, max_digits=5)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investment')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.investor')),
            ],
            options={
                'unique_together': {('investment', 'investor')},
            },
        ),
    ]
