# Generated by Django 5.1.6 on 2025-09-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_expensecategory_calltype_category_investment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.expensecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ExpenseItem',
        ),
    ]
